name: restaurent_meal_monkey
description: "Restaurant Owner App for Meal Monkey Food Delivery Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  get: ^4.6.6
  
  # UI & Design
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7
  lottie: ^3.1.2
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  
  # Backend Integration
  http: ^1.1.0
  dio: ^5.4.0
  socket_io_client: ^2.0.3+1
  
  # Image Handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utilities
  url_launcher: ^6.2.2
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  geolocator: ^10.1.0
  
  # Charts & Analytics
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
